// The vault is reached through the brain. These are the calls the guard refuses, the ones
// it must never refuse, and what it tells the caller to do instead.

import { describe, expect, test } from "bun:test";
import { guardToolCall } from "../src/guard";

const VAULT = "/mnt/disk/second brain";
const served = new Set(["Notes/rust/borrow.md"]);
const guard = (tool: string, input: Record<string, unknown>, extra: { served?: Set<string>; isDirectory?: (p: string) => boolean } = {}) =>
	guardToolCall({ tool, input, vault: VAULT, served: extra.served ?? served, isDirectory: extra.isDirectory });

describe("searching the vault from outside", () => {
	test("Grep, Glob and a directory listing are refused, and told where to go", () => {
		for (const [tool, input] of [
			["Grep", { pattern: "tailscale", path: `${VAULT}/00 Notes` }],
			["Glob", { pattern: `${VAULT}/**/*.md` }],
			["LS", { path: VAULT }],
		] as const) {
			const decision = guard(tool, input);
			expect(decision.allow).toBe(false);
			expect(decision.reason).toContain("recall");
		}
	});

	test("a shell search of the vault is refused, a shell write to it is not", () => {
		expect(guard("Bash", { command: `rg -n "tailscale" "${VAULT}"` }).allow).toBe(false);
		expect(guard("Bash", { command: `find "${VAULT}" -name '*.md'` }).allow).toBe(false);
		expect(guard("Bash", { command: `cd "${VAULT}" && ls 01 Journals` }).allow).toBe(false);
		expect(guard("Bash", { command: `cat > "${VAULT}/Inbox/note.md" <<'EOF'\nhello\nEOF` }).allow).toBe(true);
		expect(guard("Bash", { command: `git -C "${VAULT}" status` }).allow).toBe(true);
	});

	test("everything outside the vault is none of its business", () => {
		expect(guard("Grep", { pattern: "foo", path: "/home/john/Projects" }).allow).toBe(true);
		expect(guard("Bash", { command: "rg -n TODO src/" }).allow).toBe(true);
		expect(guard("Read", { file_path: "/home/john/Projects/x/README.md" }).allow).toBe(true);
	});
});

describe("reading one note", () => {
	test("a note the brain handed over is readable", () => {
		expect(guard("Read", { file_path: `${VAULT}/Notes/rust/borrow.md` }).allow).toBe(true);
	});

	test("a note nothing pointed at is refused, and the refusal names the path and the tool", () => {
		const decision = guard("Read", { file_path: `${VAULT}/Notes/rust/other.md` });
		expect(decision.allow).toBe(false);
		expect(decision.reason).toContain("Notes/rust/other.md");
		expect(decision.reason).toContain("read");
	});

	test("images and other attachments beside a note are not the brain's to gate", () => {
		expect(guard("Read", { file_path: `${VAULT}/Design Library/_images/abc.png` }).allow).toBe(true);
		expect(guard("Read", { file_path: `${VAULT}/notes.pdf` }).allow).toBe(true);
	});

	test("a directory is never a read", () => {
		const decision = guard("Read", { file_path: `${VAULT}/00 Notes` }, { isDirectory: () => true });
		expect(decision.allow).toBe(false);
	});

	test("writing and editing stay open: the recording protocol has to work", () => {
		expect(guard("Write", { file_path: `${VAULT}/Inbox/new.md` }).allow).toBe(true);
		expect(guard("Edit", { file_path: `${VAULT}/Notes/rust/other.md` }).allow).toBe(true);
	});

	test("no vault, no opinion", () => {
		expect(guardToolCall({ tool: "Grep", input: { path: "/anything" }, vault: "", served: new Set() }).allow).toBe(true);
	});
});

describe("what counts as a prompt worth remembering", () => {
	test("the harness's own machinery is not the user speaking", async () => {
		const { isSynthetic } = await import("../src/transcript");
		expect(isSynthetic("<task-notification> <task-id>abc</task-id> done")).toBe(true);
		expect(isSynthetic("<command-name>/model</command-name>")).toBe(true);
		expect(isSynthetic("Caveat: The messages below were generated by the user")).toBe(true);
		expect(isSynthetic("[Request interrupted by user]")).toBe(true);
		expect(isSynthetic("  <system-reminder>stuff</system-reminder>")).toBe(true);
		expect(isSynthetic("Fix the tailscale thing, every peer shows offline")).toBe(false);
		expect(isSynthetic("<- that arrow is just how I write")).toBe(false);
	});
});
